8: Albania
20: Andorra
32: Argentina
51: Armenia
36: Australia
40: Austria
31: Azerbaijan
50: Bangladesh
112: Belarus
68: Bolivia
70: Bosnia Herzegovina
76: Brazil
100: Bulgaria
124: Canada
152: Chile
156: China
170: Colombia
191: Croatia
196: Cyprus
203: Czechia
208: Denmark
218: Ecuador
818: Egypt
422: Lebanon
434: Libya
440: Lithuania
446: Macao SAR
458: Malaysia
462: Maldives
484: Mexico
496: Mongolia
499: Montenegro
504: Morocco
104: Myanmar
528: Netherlands
554: New Zealand
558: Nicaragua
566: Nigeria
807: North Macedonia
909: Northern Ireland
578: Norway
586: Pakistan
604: Peru
608: Philippines
616: Poland
620: Portugal
233: Estonia
231: Ethiopia
246: Finland
250: France
268: Georgia
276: Germany
826: Great Britain
300: Greece
320: Guatemala
344: Hong Kong SAR
348: Hungary
352: Iceland
360: Indonesia
364: Iran
368: Iraq
380: Italy
392: Japan
400: Jordan
398: Kazakhstan
404: Kenya
417: Kyrgyzstan
428: Latvia
630: Puerto Rico
642: Romania
643: Russia
688: Serbia
702: Singapore
703: Slovakia
705: Slovenia
410: South Korea
724: Spain
752: Sweden
756: Switzerland
158: Taiwan ROC
762: Tajikistan
764: Thailand
788: Tunisia
792: Turkey
804: Ukraine
840: United States
858: Uruguay
862: Venezuela
704: Vietnam
716: Zimbabwe